all:
  vars:
    testvariables: questo_è _un_test
  hosts:
    localhost:
      ansible_host: localhost
      ansible_connection: local
  site:
    hosts:
      localhost:
        ansible_connection: local